In [1]:
import numpy as np

a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
c=np.array([[[3,4,5],[7,8,9]]])
print(c)

[[[3 4 5]
  [7 8 9]]]


In [6]:
d=np.array([[[[1,2],[3,4]]]])
print(d)

[[[[1 2]
   [3 4]]]]


In [9]:
e=np.array(["santhosh"])
print(e)

['santhosh']


In [10]:
arr=np.zeros([3,4])
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
arr=np.ones([2,3])
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [16]:
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [21]:
arr=np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [24]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [25]:
print(arr.shape)

(2, 3)


In [26]:
print(arr.ndim)

2


In [27]:
print(arr.size)

6


In [28]:
print(arr.dtype)

int64


In [29]:
arr=np.array([10,20,30,40])
print(arr[0])
print(arr[2])

10
30


In [30]:
print(arr[-1])

40


In [32]:
arr=np.array([[1,2,3],
              [4,5,6]])
print(arr[0,1])
print(arr[1,2])

2
6


In [36]:
arr=np.array([10,20,30,40,50,60])
print(arr[1:4])

[20 30 40]


In [37]:
print(arr[:3])

[10 20 30]


In [38]:
print(arr[3:])

[40 50 60]


In [39]:
print(arr[::2])

[10 30 50]


In [41]:
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(arr[0:2,1:3])

[[2 3]
 [5 6]]


In [42]:
arr=np.arange(1,13)
new_arr=arr.reshape(3,4)
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [43]:
arr=np.arange(1,13)
new_arr=arr.reshape(2,2,3)
print(new_arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [44]:
arr=np.array([[1,2],
              [3,4]])
print(arr.flatten())

[1 2 3 4]


In [3]:
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [4]:
print(a+10)
print(a*2)

[11 12 13]
[2 4 6]


In [8]:
arr=np.array([10,20,30,40,50])
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))

150
30.0
50
10
14.142135623730951


In [11]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr.shape)
print(arr.dtype)
print(arr.size)

(10,)
int64
10


In [16]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(arr)
print(arr[0:10])
print(arr[-5:])
print(arr[5:9])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  2  3  4  5  6  7  8  9 10]
[16 17 18 19 20]
[6 7 8 9]


In [26]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr=arr.reshape(3,4)
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
new_arr=arr.reshape(2,6)
print(new_arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [27]:
a=np.array([3,4,5])
b=np.array([6,7,8])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 9 11 13]
[-3 -3 -3]
[18 28 40]
[0.5        0.57142857 0.625     ]
